[project]
name = "schroedinger_bridge_pinn"
version = "0.1.0"
description = "A Python package for solving the Schrödinger Bridge equation using Physics-Informed Neural Networks"
authors = [{name = "Robert Ziegler", email = "roziegler@student.ethz.ch"}]
readme = "Readme.md"
#requires-python = ">=3.10.13"
requires-python = ">=3.12.0"

dependencies = [
    "torch==2.5.1+cu121",
    "pytorch-lightning",
    "numpy",
    "matplotlib",
    "ipykernel",
    "wandb",
    "diffrax",
    "optax",
    "equinox",
    "tk",
    "jax[cuda12]",
    "pandas",
]

[dependency-groups]
dev = [
    "ruff~=0.12.7",
    "pytest~=8.4.1",
    "pyright~=1.1.403",
    "deptry~=0.23.1",
]


[[tool.uv.index]]
name = "pytorch-index"
url = "https://download.pytorch.org/whl/"
explicit = true

[[tool.uv.index]]
name = "pytorch-index-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-index"},
]


[tool.pyright]
reportMissingImports = false
useLibraryCodeForTypes = true # default Pylance behavior
reportPrivateImportUsage = false # too many false positives from bad PyTorch stubs
executionEnvironments = [
    { root = ".", extraPaths = ["../voize_pycore", "../voize_nn" ]}
]
include = ["src"]